version: '3.2'

services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
